### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by radium0090** [radium0090/ExChanger#19]
### task

- [ ] fix the Ads not showing problem in main screen
- [ ] do some test if any other bug found, fix it
- [ ] make pull request
