### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by radium0090** [radium0090/ExChanger#20]
### task

- [ ] fix the dark mode problem
- [ ] do some test
- [ ] make pull request

**Comment by radium0090** [comment]
ok
